### ISSUE TITLE
Insufficient documentation

### ISSUE THREAD

**Issue by BPennie03** [ReeseHatfield/MudScript#1]
**Who are you?**
Braden Pennie

**What feature do you want?**
I feel as though there is insufficient documentation and comments throughout the code, which make it hard to understand. The complexity of the code is pretty high, and the lack of comments hurts my brain.

**Why do you want this feature?**
To make the code easier to read and understand

**Additional context**
The image below depicts the main code which only contains 1 comment :(
![image](https://github.com/ReeseHatfield/MudScript/assets/89539573/700466ef-3bda-4337-bcd4-0530cae40d5b)

**Comment by ReeseHatfield** [comment]
# Issue 1: Insufficient documentation 
## Fix:
Sufficient documentation added to src files in comments

## Thanks
Thank you for raising this issue to my attention
